### PR TITLE
update Hitachi's manual.csv(s) for Discovery (DID support)

### PR DESCRIPTION
**Pull request by k-toumura**
Preliminary support for introduction using DID.
Each thing can discover using DID
-  `did:web:k-toumura.github.io:didwebtest:acc-air`
-  `did:web:k-toumura.github.io:didwebtest:led`

For example, using [DIDKit](https://spruceid.dev/docs/didkit/), you can resolve these DIDs as follows:
```sh
% didkit did-resolve did:web:k-toumura.github.io:didwebtest:led
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    {
      "Ed25519VerificationKey2018": "https://w3id.org/security#Ed25519VerificationKey2018",
      "publicKeyJwk": {
        "@id": "https://w3id.org/security#publicKeyJwk",
        "@type": "@json"
      }
    }
  ],
  "id": "did:web:k-toumura.github.io:didwebtest:led",
  // ...
  "service": [{
    "id": "did:web:k-toumura.github.io:didwebtest:led#td",
    "type": "WotThingDescription",
    "serviceEndpoint": "https://raw.githubusercontent.com/w3c/wot-testing/main/events/2022.03.Online/TD/hitachi-node-red/TDs/hitachi-led.td.jsonld"
  }]
}
%
```

### CODE REVIEW

**Comment by mmccool** [comment]
Awesome!  Merging, will update implementation report.

**Comment by mmccool** [comment]
So I updated the implementation report using this new data: https://github.com/w3c/wot-discovery/pull/346
Note that since there are two implementations, since we are counting implementations rather than organizations, DID is no longer marked as at-risk.  However... we will have to discuss in general whether we want to count two implementations from the same organization separately but for now that's the way the tooling is set up.

**Comment by mmccool** [comment]
I'm also wondering whether this also satisfies some other assertions.  In particular, you are using github to serve TDs, and this may satisfy some of the TD Server assertions.

**Comment by k-toumura** [comment]
Since current situation is 'one organization is using one DID method', so I think it would be good to have implementation from another organization or using another DID method.

And, some TD server assertion is fail because the content-type is `text/plain` when the TD is retrieved from the above GitHub URL (`service-http-resp-content-type`: _A successful response with JSON serialization MUST contain `application/json` or more specifically, `application/td+json` in the Content-Type header._).

**Pull request merged**
