### PR TITLE
Add ditto TM example for Bosch.IO

### PR DESCRIPTION
**Pull request by egekorkan**

### CODE REVIEW

**Comment by egekorkan** [comment]
@FadySalama and @mmccool I think I have put it in the correct place, following the pattern we already have at https://github.com/w3c/wot-testing/tree/main/events/2021.09.Online/TD/TMs . It would be good to merge this if it is correct since @thjaeckle will provide TMs and TDs soon.

**Comment by thjaeckle** [comment]
@egekorkan should the directory structure not be instead:
* `events/2022.03.Online/TD/Ditto/TDs`
* `events/2022.03.Online/TD/Ditto/TMs`

That's what I saw in the [Readme](https://github.com/w3c/wot-testing/tree/main/events/2022.03.Online).

**Comment by egekorkan** [comment]
That is correct, I will fix that

**Comment by egekorkan** [comment]
Done :)

**Comment by sebastiankb** [comment]
going to merge since we have a good prototype how the structure should look like

**Pull request merged**
