### PR TITLE
Add manual.csv for DNS-SD CoAP implementation

### PR DESCRIPTION
**Pull request by JKRhb**
Under https://github.com/JKRhb/wot-coap-dns-sd, I created a very simple implementation of a CoAP server with DNS-DS support, which should be able to cover one of the two remaining DNS-SD assertions from the Discovery specification (namely [`introduction-dns-sd-service-name-udp`](https://w3c.github.io/wot-discovery/#introduction-dns-sd-service-name-udp)).

I plan to perform a last couple of interoperability tests with `dart_wot` and still need to add an implementation description, therefore I only opened this PR as a draft for now. I hope that it can be merged during the upcoming discovery call.

### CODE REVIEW

**Comment by JKRhb** [comment]
I now also added basic DNS-SD support (using multicast DNS) to `dart_wot` (see https://github.com/namib-project/dart_wot/pull/27), which enabled me to test the implementation and apply a couple of minor fixes/workarounds (as I also noticed a small bug in the `wot-td` crate, which I am using to create the TD, see https://github.com/sifis-home/wot-td/pull/101).

Based on the current state of the implementation, I think this PR should now be ready to be merged :)

**Comment by JKRhb** [comment]
The PR now also features an implementation description.

**Comment by mmccool** [comment]
Please also add CSV file (named after implementation) to Results directory.  Can just be a copy of the manual.csv if you have no automatic results.

**Comment by JKRhb** [comment]
The results directory is now updated. However, there seems to be an issue with the GitHub Actions workflow not having the permission to post the `output.txt` file. For reference, you can find the `output.txt` that can be generated locally here:

### Discovery spec assertion coverage report
- coverage: 71.61%
- at-risk assertions: 44
<details>
  <summary>list of at-risk assertions</summary>

  - [discoverer-fetch-tdd](https://w3c.github.io/wot-discovery#discoverer-fetch-tdd): pass=1
  - [discoverer-fetch-links](https://w3c.github.io/wot-discovery#discoverer-fetch-links): pass=1
  - [discoverer-fetch-iteration](https://w3c.github.io/wot-discovery#discoverer-fetch-iteration): pass=1
  - [discoverer-track](https://w3c.github.io/wot-discovery#discoverer-track): pass=1
  - [introduction-direct-directory-description](https://w3c.github.io/wot-discovery#introduction-direct-directory-description): pass=1
  - [introduction-dns-sd-service-name-udp](https://w3c.github.io/wot-discovery#introduction-dns-sd-service-name-udp): pass=1
  - [introduction-dns-sd-service-name-directory-udp](https://w3c.github.io/wot-discovery#introduction-dns-sd-service-name-directory-udp): pass=0
  - [exploration-link-description-type](https://w3c.github.io/wot-discovery#exploration-link-description-type): pass=1
  - [exploration-link-description-link](https://w3c.github.io/wot-discovery#exploration-link-description-link): pass=1
  - [security-bootstrapping-endpoints](https://w3c.github.io/wot-discovery#security-bootstrapping-endpoints): pass=0
  - [exploration-secboot-401](https://w3c.github.io/wot-discovery#exploration-secboot-401): pass=1
  - [exploration-secboot-auth](https://w3c.github.io/wot-discovery#exploration-secboot-auth): pass=1
  - [exploration-secboot-oauth2-flows](https://w3c.github.io/wot-discovery#exploration-secboot-oauth2-flows): pass=0
  - [exploration-server-http-alternate-content](https://w3c.github.io/wot-discovery#exploration-server-http-alternate-content): pass=1
  - [exploration-server-http-alternate-language](https://w3c.github.io/wot-discovery#exploration-server-http-alternate-language): pass=0
  - [exploration-server-coap-size2](https://w3c.github.io/wot-discovery#exploration-server-coap-size2): pass=1
  - [tdd-absolute-time](https://w3c.github.io/wot-discovery#tdd-absolute-time): pass=1
  - [tdd-registrationinfo-expiry-config](https://w3c.github.io/wot-discovery#tdd-registrationinfo-expiry-config): pass=1
  - [tdd-http-error-response-lang](https://w3c.github.io/wot-discovery#tdd-http-error-response-lang): pass=0
  - [tdd-http-alternate-language](https://w3c.github.io/wot-discovery#tdd-http-alternate-language): pass=0
  - [tdd-http-representation-alternate-output](https://w3c.github.io/wot-discovery#tdd-http-representation-alternate-output): pass=1
  - [tdd-things-list-pagination-order](https://w3c.github.io/wot-discovery#tdd-things-list-pagination-order): pass=0
  - [tdd-things-list-pagination-orderable](https://w3c.github.io/wot-discovery#tdd-things-list-pagination-orderable): pass=0
  - [tdd-things-list-pagination-order-nextlink](https://w3c.github.io/wot-discovery#tdd-things-list-pagination-order-nextlink): pass=0
  - [tdd-things-list-pagination-order-utf-8](https://w3c.github.io/wot-discovery#tdd-things-list-pagination-order-utf-8): pass=1
  - [tdd-things-list-pagination-collection](https://w3c.github.io/wot-discovery#tdd-things-list-pagination-collection): pass=1
  - [tdd-validation-response-lang](https://w3c.github.io/wot-discovery#tdd-validation-response-lang): pass=0
  - [tdd-notification-data-diff-unsupported](https://w3c.github.io/wot-discovery#tdd-notification-data-diff-unsupported): pass=0
  - [sec-tdd-throttle-queries](https://w3c.github.io/wot-discovery#sec-tdd-throttle-queries): pass=0
  - [sec-tdd-limit-query-complexity](https://w3c.github.io/wot-discovery#sec-tdd-limit-query-complexity): pass=0
  - [sec-tdd-query-watchdog](https://w3c.github.io/wot-discovery#sec-tdd-query-watchdog): pass=1
  - [sec-tdd-intro-no-observe](https://w3c.github.io/wot-discovery#sec-tdd-intro-no-observe): pass=1
  - [sec-tdd-intro-no-multicast](https://w3c.github.io/wot-discovery#sec-tdd-intro-no-multicast): pass=0
  - [sec-tdd-intro-if-multicast-required](https://w3c.github.io/wot-discovery#sec-tdd-intro-if-multicast-required): pass=0
  - [sec-tdd-intro-limit-response-size](https://w3c.github.io/wot-discovery#sec-tdd-intro-limit-response-size): pass=0
  - [sec-tdd-intro-throttling](https://w3c.github.io/wot-discovery#sec-tdd-intro-throttling): pass=0
  - [sec-self-proxy](https://w3c.github.io/wot-discovery#sec-self-proxy): pass=0
  - [priv-loc-disable-public-directories](https://w3c.github.io/wot-discovery#priv-loc-disable-public-directories): pass=0
  - [priv-loc-anonymous-tds](https://w3c.github.io/wot-discovery#priv-loc-anonymous-tds): pass=0
  - [priv-loc-gen-ids](https://w3c.github.io/wot-discovery#priv-loc-gen-ids): pass=0
  - [priv-loc-priv-dir-access](https://w3c.github.io/wot-discovery#priv-loc-priv-dir-access): pass=0
  - [priv-loc-explicit-care](https://w3c.github.io/wot-discovery#priv-loc-explicit-care): pass=0
  - [priv-loc-explicit-strip](https://w3c.github.io/wot-discovery#priv-loc-explicit-strip): pass=0
  - [priv-query-anon](https://w3c.github.io/wot-discovery#priv-query-anon): pass=0
</details>

**Comment by JKRhb** [comment]
I noticed that there are two more CoAP-related assertions the implementation fulfills. I added them at the bottom of the two `.csv` files and also updated the comment above.

@mmccool If the current state of the PR is fine, then I think it could be merged now.

**Pull request merged**
