### PR TITLE
WoTWebThing Profile implementation

### PR DESCRIPTION
**Pull request by mlagally**

### CODE REVIEW

**Comment by egekorkan** [comment]
There is an actual error where the events are under actions. They should be moved one layer up.

**Comment by egekorkan** [comment]
Also, it would be nice to have an implementation description and ideally the TD submissions should be duplicated under profiles as well.

**Comment by egekorkan** [comment]
The document is fine but Oracle is not an implementation. Please group it as the name of the implementation

**Comment by mmccool** [comment]
Will fix name thing as part of reorg.

**Comment by mmccool** [comment]
I put it under the name "oracle-wt" to not get merged into the older "Oracle" implementation (including bluePump, etc) that I am already using from a previous plugfest.  Do these use the same codebase, i.e. SHOULD we be grouping them under a single directory with the digital twin stuff?

**Pull request merged**
