### PR TITLE
Update manual.csv for dart_wot

### PR DESCRIPTION
**Pull request by egekorkan**
Following the comment of @JKRhb in the assertion slides. @JKRhb please let us know if this is not correct.

Screenshot 2023-05-11 at 13 57 17

### CODE REVIEW

**Comment by JKRhb** [comment]
Thank you for updating the `manual.csv` file, @egekorkan! :) After checking again, I think this could be merged – by default, the HTTPS implementation within `dart_wot` does not use a client certificate, so this assertion should be covered :)

**Comment by JKRhb** [comment]
Maybe a follow-up question, though: From my understanding, this assertion can be fulfilled by a Consumer – is that correct? Or do you need a server to cover it? (In the latter case this assertion would not be fulfilled.)

**Comment by egekorkan** [comment]
Well now that you mention it, I think that this assertion can be fulfilled both by a Thing and Consumer. Given that dart_wot actually runs on people's phones, the "associated with person" part is very correct.

**Comment by JKRhb** [comment]
> Well now that you mention it, I think that this assertion can be fulfilled both by a Thing and Consumer. Given that dart_wot actually runs on people's phones, the "associated with person" part is very correct.

Thank you for clarifying! :) Then I suppose this PR could be merged :)

**Pull request merged**
