### PR TITLE
Discovery: Add results for siemens-logilab

### PR DESCRIPTION
**Pull request by ethieblin**
- manual.csv was manually filled based on Discovery/manual.csv
- auto.csv was created using https://github.com/farshidtz/wot-discovery-testing
  - Note: some tests are skipped in @farshidtz tool (they are "skipped" in auto.csv and they do not appear in "manual.csv" template such as `tdd-registrationinfo-vocab-ttl`)
  - Note: the tool has some JSON-LD comparison issues making some of the tests fail (namely https://github.com/farshidtz/wot-discovery-testing/issues/26, https://github.com/farshidtz/wot-discovery-testing/issues/24 and https://github.com/farshidtz/wot-discovery-testing/issues/6)

### CODE REVIEW

**Comment by farshidtz** [comment]
The JSON-LD comparison is not an issue anymore. I've just merged a PR that works around this issue: https://github.com/farshidtz/wot-discovery-testing/pull/29

**Comment by mmccool** [comment]
at @ethieblin request, will hold for an hour for an update.

**Comment by farshidtz** [comment]
I have remove the "skipped" registration info tests, which were just in my to do list to implement. Going to make a PR to add them to the manual.csv until I do implement them.

**Comment by ethieblin** [comment]
@mmccool auto.csv has been updated with the latest version of the tool

**Pull request merged**
