### PR TITLE
Provide ditto.csv for architecture results

### PR DESCRIPTION
**Pull request by thjaeckle**
@egekorkan I tried to fill out everything to my best knowledge :)
Feedback is much appreciated.

### CODE REVIEW

**Comment by egekorkan** [comment]
Looking good to me :)

**Comment by mmccool** [comment]
I'm going to go ahead and merge it so I can updated the Architecture implementation report.  If we discover any issue we can fix them with another PR.

**Comment by mmccool** [comment]
I see it's also going into data/input_2022.  Oh well... however, I will move it over to the events/2022.09.Online directory to keep things consistent.

**Review by mmccool — APPROVED** [review]
OK, but going to wrong directory.  However, to expedite things, I will merge it and then move it.

**Pull request merged**
