### PR TITLE
TM smart coffee machine

### PR DESCRIPTION
**Pull request by sebastiankb**
First TM version of the smart coffee machine

### CODE REVIEW

**Comment by egekorkan** [comment]
One thing we should start doing already would be to name TM files in a way to associate them with the TDs. I think here it is quite clear but a specific naming template would be nice since we can have more TMs showing up this plugfest. E.g. myThing.td.jsonld and myThing.tm.jsonld

**Comment by mmccool** [comment]
I see .td+jsonld is being used in the PR for TDs, then just plain .jsonld for TMs.  How about .td+jsonld for TDs and .tm+jsonld for TMs?

**Comment by k-toumura** [comment]
Using `+` character in filename may be legal, but if use it in URL, it is escaped to `%2B` and is somewhat confusing...
e.g. `https://github.com/w3c/wot-testing/blob/b118f51/events/2021.03.Online/TMs/Siemens/Smart-Coffee-Machine-TD.td%2Bjson`

**Comment by sebastiankb** [comment]
I renamed the TM to `tm+json` since this will be kind of aligned with `td+json`

@k-toumura 
Thats right, but browser also typically take the form 
https://github.com/w3c/wot-testing/blob/b118f51/events/2021.03.Online/TMs/Siemens/Smart-Coffee-Machine-TD.td+json
and may transform the character + for you.

**Comment by relu91** [comment]
My comment on the _plus notation_ : 
>The problem with the second proposal (tm+jsonld) is that IDEs will not recognize them as jsonld files. So if they don't support TD or TM syntax highlighter they will not fallback to jsonld but simply text.

> Moreover, I am not sure if the plus notation is common for file extensions. 🤔

**Comment by egekorkan** [comment]
I second what @relu91 says. I think that the + notation used for media types translates to a dot in filenames. The media type + denotes that the content is json but a special kind of json. It can still be parsed as a JSON. To have the same for filenames (process it as a JSON but allow more specific tooling on top of it), we have to end with .json . Then we can put _specifiers_ in front of it.

**Comment by mmccool** [comment]
Because of the IDE things (eg highlighting in vi) using .td.jsonld and .tm.jsonld seems to make the most sense, and also works for wildcards.   ASDF also uses .sdf.json, so this is somewhat consistent.   Discussed in PF meeting, @sebastiankb will update PR, and I will merge.   Then @mmccool will update other TDs and update the README.   Note though that some IDEs won't recognize .jsonld... so something like .td.ld.json, but this is not the JSON-LD group's recommendation.   So we will stick with .td.jsonld.

**Pull request merged**
