### PR TITLE
Add manual.csv files for `dart_wot`

### LINKED ISSUE #307: Adding dart_wot to implementations
I have just realized that dart_wot by @JKRhb is not in the list of implementations. It is already public at https://pub.dev/packages/dart_wot and if @JKRhb agrees to, it would be nice to have it as a consumer implementation. This would mean writing an implementation description and filling the manual.csv for only the consumer related parts

### PR DESCRIPTION
**Pull request by JKRhb**
Resolves #307. This PR only contains the empty manual.csv files for now, which will be filled over the next few days.

### CODE REVIEW

**Comment by egekorkan** [comment]
@JKRhb is this ready?

**Comment by JKRhb** [comment]
> @JKRhb is this ready?

Unfortunately, I still need to fill the table, I hope to get it done in the next two hours :)

**Comment by JKRhb** [comment]
@egekorkan Sorry that it took so long, the PR is now ready :)

**Comment by JKRhb** [comment]
Made some last minute improvements, should actually be ready now :)

**Pull request merged**
