### PR TITLE
Add Discovery manual.csv for RIOT OS implementation

### PR DESCRIPTION
**Pull request by JKRhb**
This is another CoAP-related manual.csv file for the RIOT OS implementation @Citrullin and I are working on (see [here](https://github.com/namib-project/wot-nodes) for a couple of example applications for ESP32 using it). There are two assertions which I would consider failed (the one regarding the `Size2` option and the one regarding content negotiation) but these could probably be fixed before Wednesday.

### CODE REVIEW

**Comment by JKRhb** [comment]
Updated the PR with test results for content negotiation.

**Comment by JKRhb** [comment]
I noticed that the [assertion](https://w3c.github.io/wot-discovery/#sec-tdd-intro-no-observe) for not supporting observe for introduction mechanisms is also fulfilled by the implementation and included it in the `manual.csv` file.

**Comment by mmccool** [comment]
Great, thanks!   I am going to merge, cleanup, and fold into the IR.

**Comment by Citrullin** [comment]
> This is another CoAP-related manual.csv file for the RIOT OS implementation @Citrullin and I are working on (see [here](https://github.com/namib-project/wot-nodes) for a couple of example applications for ESP32 using it). There are two assertions which I would consider failed (the one regarding the `Size2` option and the one regarding content negotiation) but these could probably be fixed before Wednesday.

Big thank you. 😊

**Pull request merged**
