### PR TITLE
Fix renaming VAIMEE folder to Zion

### PR DESCRIPTION
**Pull request by relu91**
As discussed in https://github.com/w3c/wot-thing-description/pull/1838, I'm renaming the VAIMEE folder to Zion. Let me know if there is anything I should add/do.

### CODE REVIEW

**Review by egekorkan — APPROVED** [review]

**Comment by relu91** [comment]
@egekorkan what happened with validation? is there anything I should fix? 🤔

**Comment by egekorkan** [comment]
Nothing you can do apparently :( We need to either use npm workspaces (which has issues with playground or go back to lerna 6).

**Comment by egekorkan** [comment]
@relu91 can you pull changes from master? I have fixed the lerna version at #585

**Comment by relu91** [comment]
Done ☑️

**Pull request merged**
