### PR TITLE
feat: add TDs and TMs from Siemens

### PR DESCRIPTION
**Pull request by danielpeintner**

### CODE REVIEW

**Comment by danielpeintner** [comment]
Mhh, the validation checkers seems to be to strict to me, see https://github.com/w3c/wot-testing/runs/3685244907

It requires 
* for properties writeOnly and readOnly.
* for actions safe and idempotent

All of them have default values ... I think without should be sufficient. Please find below the sample I used.

https://github.com/w3c/wot-testing/blob/83d1ce6fb79cf7e01abd50cc10f3dafef17a2d55/events/2021.09.Online/TD/TDs/Siemens/ecar.td.jsonld

@egekorkan is this properly setup?

**Comment by egekorkan** [comment]
It is not properly set up, there is no requirement on defaults to be filled

**Comment by egekorkan** [comment]
`-d` options should be used in order to turnoff full validation https://github.com/w3c/wot-binding-templates/issues/124

**Comment by ashimura** [comment]
Is there any turnaround option (e.g., adding "-d" to the GitHub action) to avoid the "All checks have ailed" GitHub error above?

**Comment by danielpeintner** [comment]
> Is there any turnaround option (e.g., adding "-d" to the GitHub action) to avoid the "All checks have ailed" GitHub error above?

Yes, I think this is what someone needs to do...

@egekorkan  can you fix the GH workflow?

Is it correct that we need to change

https://github.com/w3c/wot-testing/blob/9e785fe9fb60a204fba4ec09fe1444280f348756/.github/workflows/validation.yaml#L45

to

`result=$(node $VALIDATION_SCRIPT -d $file)`

?

**Comment by danielpeintner** [comment]
FYI: https://github.com/w3c/wot-testing/pull/151

Please approve/merge if this is correct.

**Comment by danielpeintner** [comment]
Yet another unrelated error

https://github.com/w3c/wot-testing/pull/150/checks?check_run_id=3716935098

```
Validating events/2021.09.Online/TD/TDs/Siemens/counter.td.jsonld ...
node:internal/fs/utils:323
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'node_modules/@thing-description-playground/core/examples/tds'
    at Object.lstatSync (node:fs:1129:3)
    at coreValidation (/home/runner/work/wot-testing/wot-testing/thingweb-playground/packages/cli/index.js:330:11)
    at Object.<anonymous> (/home/runner/work/wot-testing/wot-testing/thingweb-playground/packages/cli/index.js:142:5)
```

**Comment by danielpeintner** [comment]
@egekorkan ?

**Comment by egekorkan** [comment]
I am looking into it. No idea why it looks for the examples

**Comment by egekorkan** [comment]
The mistake was to use -d option before the filename. Now it works on my computer but I get the same error as if the validation.yaml is not changed

**Comment by farshidtz** [comment]
> The actions page still says `result=$(node $VALIDATION_SCRIPT -d $file)` even though I have changed it twice now. Maybe it needs some time

You have changed the YAML file on another branch. You need to change the one on your branch:
https://github.com/danielpeintner/wot-testing/blob/testfest-2021-09-siemens/.github/workflows/validation.yaml#L45

**Comment by egekorkan** [comment]
> > The actions page still says `result=$(node $VALIDATION_SCRIPT -d $file)` even though I have changed it twice now. Maybe it needs some time
> 
> You have changed the YAML file on main branch. You need to change the one on your branch because that's what this PR executes:
> https://github.com/danielpeintner/wot-testing/blob/testfest-2021-09-siemens/.github/workflows/validation.yaml#L45

I confirm that this works as intended :)

**Pull request merged**
