### PR TITLE
Add TMs and `manual.csv` for sdf-wot-converter

### PR DESCRIPTION
**Pull request by JKRhb**
This PR adds a number of SDF models from the [oneDM
playground](https://github.com/one-data-model/playground), converted with my [SDF WoT Converter](https://github.com/JKRhb/sdf-wot-converter-py) to WoT TMs. As my converter is also capable of TM ⇋ TD conversion, I also added a manual.csv file containing test results for the TM-related assertions.

### CODE REVIEW

**Comment by egekorkan** [comment]
Really cool thanks! One issue might be that you have submitted a lot so that the tooling will take quite some more time. If there are repetitive stuff, I think you can omit them

**Comment by JKRhb** [comment]
Thank you for the feedback, @egekorkan :) 

> One issue might be that you have submitted a lot so that the tooling will take quite some more time. If there are repetitive stuff, I think you can omit them

Yeah, I was thinking the same, I think I'll draw a sample of maybe 10 models so that the testing procedure does not get slowed down too much.

By the way, I noticed that the `thingweb-playground` module cannot handle the `tm:required` feature at the moment (see https://github.com/thingweb/thingweb-playground/issues/273, CC @FadySalama), causing errors in the batchValidation script.

**Comment by egekorkan** [comment]
JSON Pointer format (`format:"json-pointer"`) seems to be wrong somehow. We will investigate

**Comment by mmccool** [comment]
Is this ready to merge yet?  It would be helpful to do so I can update the implementation reports, even if it is not finalized.  Currently it seems to pass validation but is still marked as draft.

**Comment by mmccool** [comment]
My preference would be to merge this, and resolve the issue with the json-pointer format separately.  Note that RFC6901 defines JSON Pointer as a value to be used as a fragment identifier, NOT a URI.  The TD spec should be consistent with the RFC, not with ajv.   Also, the # means it is a fragment identifier and a relative URL.  So if it's a "pure" JSON Pointer it should not have the #.  If it is a relative URL with a JSON Pointer, then it should have the #.

Actions:
- Review the TD spec to make sure it is using JSON Pointer consistently with the RFC, and update examples, etc. if necessary.

**Comment by JKRhb** [comment]
Thank you for your feedback on this, @mmccool! I would update the submitted models, as there are a couple of fixes I introduced in the latest version of my converter. Then the PR should be ready to be merged. Is it fine to keep all models? Or should I draw a sample (of maybe 10 or 20 %) and remove the rest?

**Comment by mmccool** [comment]
Let's merge all of them to get maximum coverage.  However, can you change the PR to merge into data/input_2022 as described in the README?  Then I will merge as soon as the CI tooling finishes (hopefully by tomorrow's Testfest sync call).

**Comment by JKRhb** [comment]
> Let's merge all of them to get maximum coverage. However, can you change the PR to merge into data/input_2022 as described in the README? Then I will merge as soon as the CI tooling finishes (hopefully by tomorrow's Testfest sync call). Note: if there are still fixes to be made, you can do spot fixes...

Done :) I also addressed the issues with the JSON pointers in the `tm:required` arrays both in the converter and the resulting TMs, so the validation should not fail anymore.

**Review by egekorkan — APPROVED** [review]
Thanks!

**Review by mmccool — APPROVED** [review]

**Comment by mmccool** [comment]
@JKRhb we merged this, and I have since done some cleanup in the batchValidation.sh script, however there seems to be an issue with some of your files having neither an id or a title.  While both are in fact optional, it seems to be a limitation of the assertion tester that it needs one or the other, and needs them to be unique within a set of TDs/TMs (and if both are missing, and two such files exist, they seem to be considered duplicates).  So I have not been able to incorporate your results.

The easiest fix would be to add a unique title to all files, perhaps based on the filename.  However, since there are over a hundred files, I don't want to do this manually.  Do you think you can update your conversion script to do something like that?

**Comment by mmccool** [comment]
To be semi-clearer, here is what happens:
```
sdf-wot-converter
Checking TMs...
Checking Assertions...
progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | TM Name: {tmName} | 0/186 
progress [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 1% | TM Name: Acidity575 | 2/186 
progress [█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 2% | TM Name: Actuation823 | 4/186 
progress [█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 3% | TM Name: NaN | 6/186 
/home/mmccool/Dev/thingweb-playground/packages/assertions/index.js:172
                if (jsonResults[tmName] !== undefined) {throw new Error("TDs have same Ids or titles: " + tmName)}
                                                              ^

Error: TDs have same Ids or titles: NaN
    at /home/mmccool/Dev/thingweb-playground/packages/assertions/index.js:172:63
    at Array.forEach (<anonymous>)
    at /home/mmccool/Dev/thingweb-playground/packages/assertions/index.js:158:23
```

**Comment by JKRhb** [comment]
Thanks for the feedback and the error log, @mmccool!

> The easiest fix would be to add a unique title to all files, perhaps based on the filename. However, since there are over a hundred files, I don't want to do this manually. Do you think you can update your conversion script to do something like that?

Sure, I'll add it as an additional option to the converter.

Additionally (or alternatively), I opened https://github.com/thingweb/thingweb-playground/pull/318 in order to let the assertion tester accept TMs without title and id.

**Pull request merged**
